@startuml
!include C:\Users\Vpatrushev\IdeaProjects\pafp-wiki\UML_LIB\umlLib\seqLib4\SequenceLibIncludeFile_v4.puml
diagramInit(final,"TEST")
rq(Alice,Bob,++,"Текст для стрелки","Текст для таблицы")
audit(EVENT_NAME,,"a;sldfjasldkf",Bob)
rs(,,,"Text","Comment")
NOTE(,,,"Test Note")
rq(Alice,redis,,"asdf","asdf")
ORIGINAL()
@enduml